# Generated by Django 5.1.1 on 2024-09-17 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(db_comment='The org this issue belongs to.', max_length=1000)),
                ('repo', models.CharField(db_comment='The repository this issue belongs to.', max_length=1000)),
                ('issue_id', models.IntegerField(db_comment='The issue number.')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(db_comment="The github handle for the user, without the '@github' part.", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_estimate', models.IntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.githubissue')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, null=True)),
                ('estimation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estimationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.githubuser')),
            ],
        ),
    ]
