# Generated by Django 5.1.1 on 2024-09-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubuser",
            name="access_token",
            field=models.CharField(
                blank=True,
                db_comment="GitHub access token for OAuth authentication.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="githubuser",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
