# Generated by Django 5.1.1 on 2024-09-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubissue',
            old_name='issue_id',
            new_name='issue_number',
        ),
        migrations.AddField(
            model_name='githubissue',
            name='body',
            field=models.CharField(blank=True, db_comment='The issue body when fetched from the github API, in markdown format', max_length=10000, null=True),
        ),
    ]
