# Generated by Django 5.1.1 on 2024-09-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_githubuser_access_token_githubuser_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='id',
        ),
        migrations.AddField(
            model_name='githubissue',
            name='title',
            field=models.CharField(blank=True, db_comment='The issue title when fetched from the GH API', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='handle',
            field=models.CharField(db_comment="The github handle for the user, without the '@github' part.", max_length=1000, primary_key=True, serialize=False),
        ),
    ]
