postgresCluster:
  storageSize: 512Mi
  postgres:
    replicaCount: 2
  pgbouncer:
    replicaCount: 2

  # The "users" value(s) is passed to the crunchy postgres operator to create the database.
  # See https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management
  users:
    - name: postgres
      options: "SUPERUSER"
    - name: estimation
      databases:
        - estimation

gcsBackups:
  enable: false

# To configure a KNP allowing external access, for metabase for example
external-access:
  enabled: false
