apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "cas-estimation-tool.fullname" . }}
  labels:
{{ include "cas-estimation-tool.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  host: cas-estimation-tool.apps.silver.devops.gov.bc.ca
  port:
    targetPort: {{ template "cas-estimation-tool.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ template "cas-estimation-tool.fullname" . }}
    weight: 100
  wildcardPolicy: None
