apiVersion: v1
kind: Service
metadata:
  name: {{ template "cas-estimation-tool.fullname" . }}
  labels: {{ include "cas-estimation-tool.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: {{ template "cas-estimation-tool.fullname" . }}
  selector: {{ include "cas-estimation-tool.selectorLabels" . | nindent 4 }}